#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat << 'USAGE'
Usage: cleanup.sh [OPTIONS]

Clean local workstation artifacts generated by DevOps tooling.

Options:
  --cache-dir DIR          Cache directory to remove (repeatable)
  --logs-dir DIR           Logs directory to prune (repeatable)
  --days N                 Remove files older than N days from log dirs (default: 14)
  --remove-tool-cache      Remove common tool caches (~/.cache/pip, ~/.cache/helm, ~/.terraform.d/plugin-cache)
  --dry-run                Print actions without executing
  -h, --help               Show help
USAGE
}

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 2
}

log() {
  printf '%s [setup-local-cleanup] %s\n' "$(date +"%Y-%m-%dT%H:%M:%S%z")" "$*" >&2
}

run_cmd() {
  if $dry_run; then
    printf 'DRY-RUN:' >&2
    printf ' %q' "$@" >&2
    printf '\n' >&2
    return 0
  fi
  "$@"
}

remove_path() {
  local p="$1"
  [[ -n "$p" && "$p" != "/" ]] || die "refusing unsafe removal path: $p"
  [[ -e "$p" ]] || return 0
  run_cmd rm -rf -- "$p"
}

cache_dirs=()
logs_dirs=()
max_age_days=14
remove_tool_cache=false
dry_run=false

while (($#)); do
  case "$1" in
    --cache-dir)
      shift
      (($#)) || die "--cache-dir requires a value"
      cache_dirs+=("$1")
      ;;
    --logs-dir)
      shift
      (($#)) || die "--logs-dir requires a value"
      logs_dirs+=("$1")
      ;;
    --days)
      shift
      (($#)) || die "--days requires a value"
      [[ "$1" =~ ^[0-9]+$ ]] || die "--days must be a non-negative integer"
      max_age_days="$1"
      ;;
    --remove-tool-cache)
      remove_tool_cache=true
      ;;
    --dry-run)
      dry_run=true
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      die "unknown option: $1"
      ;;
  esac
  shift
done

if ((${#cache_dirs[@]} == 0)); then
  cache_dirs+=("$HOME/.cache/devops.scripts")
fi

if ((${#logs_dirs[@]} == 0)); then
  logs_dirs+=("$HOME/.local/state/devops.scripts/logs")
fi

if $remove_tool_cache; then
  cache_dirs+=("$HOME/.cache/pip" "$HOME/.cache/helm" "$HOME/.terraform.d/plugin-cache")
fi

for d in "${cache_dirs[@]}"; do
  [[ -n "$d" ]] || continue
  log "removing cache dir: $d"
  remove_path "$d"
done

for d in "${logs_dirs[@]}"; do
  [[ -d "$d" ]] || continue
  log "pruning logs older than $max_age_days days in: $d"
  if $dry_run; then
    run_cmd find "$d" -type f -mtime "+$max_age_days" -print
  else
    find "$d" -type f -mtime "+$max_age_days" -delete
  fi
done

exit 0
